### ISSUE TITLE
1.16.5 已安装MaFgLib 无法运行 报错

### ISSUE THREAD

**Issue by WX4M** [ThinkingStudios/Tweakeroo-Forge#1]
[错误报告-2023-7-9_12.52.00.zip](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/11994443/-2023-7-9_12.52.00.zip)

**Comment by TexBlock** [comment]
最新版还这样吗？

**Comment by xiaoyang5202480** [comment]
依旧这样。
芝士我的错误报告。
[错误报告-2023-7-22_19.27.30.zip](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/12136269/-2023-7-22_19.27.30.zip)


> 最新版本还这样吗？
