### ISSUE TITLE
1.19.2 无法在服务器上运行,客户端可以运行以下是日志与报告 说是无法加载Java是17的

### ISSUE THREAD

**Issue by mowenxuan** [ThinkingStudios/Tweakeroo-Forge#10]
1.19.2 Unable to run on server, client can run. The following are logs and reports
1.19.2无法在服务器上运行,客户端可以运行以下是日志与报告
[日志与报告.zip](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/13694660/default.zip)
Error:Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered

**Comment by mowenxuan** [comment]
1.19.2 Unable to run on server, client can run. The above are logs and reports
https://github.com/ThinkingStudios/Tweakeroo-Forge/files/13694660/default.zip

**Comment by TexBlock** [comment]
THIS MOD ONLY RUNNING ON CLIENT!!
