### ISSUE TITLE
请为 1.20.1 同步 tweakeroo 上游代码

### ISSUE THREAD

**Issue by ColdLemonTea** [ThinkingStudios/Tweakeroo-Forge#14]
没有自动切换鞘翅用真的要死了(x

**Comment by JackieJK** [comment]
> 没有自动切换鞘翅用真的要死了(x

上游也没有自动切换鞘翅 好消息是我移植好了[Build · Workflow runs · JackieJK/Tweakeroo-Forge](https://github.com/JackieJK/Tweakeroo-Forge/actions/workflows/build.yml)

**Comment by TexBlock** [comment]
will release a new version!
