### ISSUE TITLE
[1.18.2]0.1.5会导致tacz1.0.2的子弹无法堆叠

### ISSUE THREAD

**Issue by LMaxRouterCN** [ThinkingStudios/Tweakeroo-Forge#16]
![image](https://github.com/user-attachments/assets/bda38964-b24b-411f-a0c1-b7c3d8fff824)

**Comment by TexBlock** [comment]
暂时无法修复，可能是TACZ的问题

**Comment by LMaxRouterCN** [comment]
彳亍

**Comment by TexBlock** [comment]
找到问题所在了，我们需要mixin tacz的AmmoItem类，去实现tweakerge的一个关于item的interface

这几天可能会修复掉

**Comment by TexBlock** [comment]
请下载[这个模组](https://github.com/ThinkingStudios/TweakergeCompat/releases)，它解决了两者的冲突。
