### ISSUE TITLE
快速右键无效

### ISSUE THREAD

**Issue by Phoupraw** [ThinkingStudios/Tweakeroo-Forge#18]
启用fast right click并按住右键，并没有快速右键。
1.21.1 neo 0.1.8
[latest.log](https://github.com/user-attachments/files/18050820/latest.log)

**Comment by TexBlock** [comment]
已在0.1.9修复

**Comment by Phoupraw** [comment]
并未修复，还是原版一样的右键间隔。左键快速点击正常。
[latest.log](https://github.com/user-attachments/files/18165911/latest.log)

**Comment by Phoupraw** [comment]
刚刚发现快速右键方块限制和物品限制不知道为什么变成白名单了，我明明没动过……改成黑名单和“无”就好了。
