### ISSUE TITLE
同时开启“tweakfreecamera”与“tweakholdattack”后关闭第一个功能选项导致游戏崩溃：尝试攻击无效实体，并卡进多人模式

### ISSUE THREAD

**Issue by iPodtouch6557** [ThinkingStudios/Tweakeroo-Forge#3]
如题，如果无法复现我还能提供截图

**Comment by TexBlock** [comment]
> 如题，如果无法复现我还能提供截图

latest.log呢？

**Comment by iPodtouch6557** [comment]
现在是同时开启leftclick按住左键并且按freecamera的热键时有概率触发

[latest.log](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/12275125/latest.log)

**Comment by TexBlock** [comment]
> 现在是同时开启leftclick按住左键并且按freecamera的热键时有概率触发
> 
> [latest.log](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/12275125/latest.log)

您这是fabric，咱这边是forge移植版，你想报告原tweakeroo的bug去原仓库发issue

**Comment by iPodtouch6557** [comment]
> > 现在是同时开启leftclick按住左键并且按freecamera的热键时有概率触发
> > [latest.log](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/12275125/latest.log)
> 
> 您这是fabric，咱这边是forge移植版，你想报告原tweakeroo的bug去原仓库发issue

在哪.jpg
就是因为找不到才来这的

**Comment by TexBlock** [comment]
> > > 现在是同时开启leftclick按住左键并且按freecamera的热键时有概率触发
> > > [latest.log](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/12275125/latest.log)
> > 
> > 
> > 您这是fabric，咱这边是forge移植版，你想报告原tweakeroo的bug去原仓库发issue
> 
> 在哪.jpg 就是因为找不到才来这的

https://github.com/maruohon/tweakeroo
