### ISSUE TITLE
Mac OS ARM crash 

### ISSUE THREAD

**Issue by shenyx110** [ThinkingStudios/Tweakeroo-Forge#4]
[minecraft-exported-crash-info-2023-08-12T14-55-00.zip](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/12326778/minecraft-exported-crash-info-2023-08-12T14-55-00.zip)
[minecraft-exported-logs-2023-08-12T14-54-53.log](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/12326779/minecraft-exported-logs-2023-08-12T14-54-53.log)

Mac book pro m1 16GB

**Comment by TexBlock** [comment]
Don't have MacOS devices, can't test

**Comment by Kasualix** [comment]
安装[MaLiLib的Forge版](https://modrinth.com/mod/mafglib/versions)，Tweakerge需要它当前置。
